name: dracone
description: Flutter game engine based on fluttershy library
version: 0.1.0
homepage: "https://github.com/DraconicDevelopment/dracone"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  fluttershy: ^0.1.4
  dartex: ^0.1.15
  ordered_set: ^2.0.0
  flare_flutter: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
