name: dracone
description: A new Flutter package project.
version: 0.0.1
author: Draconic Development
homepage: "https://github.com/DraconicDevelopment/dracone"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  fluttershy: ^0.1.3
  dartex: ^0.1.14
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter